{"name": "test_add_user_already_exists", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'json'", "trace": "init_session = <infra.api_communication.Communication object at 0x000001D28F657210>\nconfiguration = Config(HOST='http://192.168.1.33', PORT='3002')\n\n    @pytest.fixture\n    def setup_teardown(init_session, configuration):\n        admin = endpoints.AdminAPI(init_session, configuration)\n>       admin.delete_all_users()\n\nconftest.py:52: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <logic.endpoints.AdminAPI object at 0x000001D2903E2A50>\n\n    def delete_all_users(self):\n>       return self.conn.delete(f\"{self.base_url}/delete_all_users\").json()\nE       AttributeError: 'NoneType' object has no attribute 'json'\n\nlogic\\endpoints.py:43: AttributeError"}, "attachments": [{"name": "log", "source": "e06ad984-7f00-4c9b-8138-39865b3c312d-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "8996d002-d29d-4077-99cb-03430bda2d80-attachment.txt", "type": "text/plain"}], "start": 1679895498186, "stop": 1679895498186, "uuid": "4f478607-61d4-4d8b-99c0-47aa7f367e29", "historyId": "d1547a7b0f7584a5cc7d5fc11e478d70", "testCaseId": "2653eaebae43387b15ebaa804ec6db84", "fullName": "tests.test_users.TestUsers#test_add_user_already_exists", "labels": [{"name": "epic", "value": "users api"}, {"name": "story", "value": "a client cant add exists usernames"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_teardown')"}, {"name": "tag", "value": "users"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_users"}, {"name": "subSuite", "value": "TestUsers"}, {"name": "host", "value": "LAP-adim"}, {"name": "thread", "value": "13804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_users"}]}