{"name": "test_add_user_already_exists", "status": "passed", "steps": [{"name": "add user {'user_name': 'adim333', 'user_password': 'LtsMOOmX'}", "status": "passed", "start": 1679905991347, "stop": 1679905991430}, {"name": "getting the user adim333", "status": "passed", "start": 1679905991430, "stop": 1679905991501}, {"name": "add user {'user_name': 'adim333', 'user_password': 'LtsMOOmX'}", "status": "passed", "start": 1679905991501, "stop": 1679905991562}], "attachments": [{"name": "log", "source": "26cf1220-5454-4841-8312-db750d000e0f-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "1f9260cd-b834-45b4-9d4c-0c888b5aab06-attachment.txt", "type": "text/plain"}], "start": 1679905991347, "stop": 1679905991562, "uuid": "354cdab2-42a9-4e6b-af98-12e384f6ffac", "historyId": "d1547a7b0f7584a5cc7d5fc11e478d70", "testCaseId": "2653eaebae43387b15ebaa804ec6db84", "fullName": "tests.test_users.TestUsers#test_add_user_already_exists", "labels": [{"name": "epic", "value": "users api"}, {"name": "story", "value": "a client cant add exists usernames"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_teardown')"}, {"name": "tag", "value": "users"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_users"}, {"name": "subSuite", "value": "TestUsers"}, {"name": "host", "value": "LAP-adim"}, {"name": "thread", "value": "14200-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_users"}]}