[32mINFO    [0m mylogger:logger.py:83 conftest.py::def setup_teardown(...)::line 55 > DELETE > 200 > {"message":"OK"}

[32mINFO    [0m mylogger:logger.py:83 conftest.py::def setup_teardown(...)::line 56 > DELETE > 200 > {"message":"OK"}

[32mINFO    [0m mylogger:logger.py:83 <setup> Cleared all users from DB
[32mINFO    [0m mylogger:logger.py:83 endpoints.py::def get_user(...)::line 78 > GET > 200 > {"error":"user myuser222 does not exist"}